Fix ARM64 intrinsics error due outdated toolset
The Windows SDK version installed in CI imposes intrinsics not supported
in the v142 toolset, thus we need to upgrade:

ClCompile target) ->
         C:\Program Files (x86)\Windows Kits\10\Include\10.0.26100.0\um\winnt.h(6343,12): error C3861: '_CountOneBits64': identifier not found [C:\Temp\builddir\DistroLauncher\DistroLauncher.vcxproj]